### ISSUE TITLE
My feedback about your module

### ISSUE THREAD

**Issue by Pierre-Gilles** [matueranet/gladys-module-network#1]
Hi ! First congrats for your first module, I read the code and did a first try of your module, but I need more explanation before I can really help you.. And I read a few mistakes in your code, these are not critics just idea how to improve this module quality ;)

First, there are a lots of promises anti-patterns in your code. When you do [that](https://github.com/matueranet/gladys-module-network/blob/master/lib/ping.js#L8) 

You don't need to create a new promise, because there is already one created by ping-bluebird ! You can simply do that : 

```javascript
module.exports = function ping(host) {
  return bluePing(host)
             .then((result) => result.alive);
}
```

It does the exact same thing as your code, but without the overhead of creating a new promise. If an error is detected, it will be thrown and returned to the promise chain before. 

`return new Promise(function(resolve, reject){});` need to be used only when you want to convert a callback based function to a promise based one. This is not the case here as ping-bluebird already use promises.

[Here](https://github.com/matueranet/gladys-module-network/blob/master/lib/ping.js#L2) little typo error :) 

I don't understand what's the goal of [the scan function](https://github.com/matueranet/gladys-module-network/blob/master/lib/scan.js#L17), can you explain it ? :) What is the lifecycle of your module ?

What's should be put inside the [network.ping.hosts param value](https://github.com/matueranet/gladys-module-network/blob/master/lib/scan.js#L17) ?

Be careful, the param store is a key value store, the goal is not to replace a database.. What's your goal here ? :)

Thanks again for your replies,

**Comment by danships** [comment]
Thanks for your feedback. The hosts param should contain a | separated value of ip addresses to monitor via ping.

The goal of the module is to check on an interval whether an ip is reachable via ping. I want to use it to detect if my phone is on my networks WiFi. If it is I can set my user status to home, and build scenarioson that.

The scanning of ips should start when Gladys starts. It now checks if there are devices for the configured ips, and adds them if there are not. The actual ping is not implemented yet, because of the Waterline validation error when creating the devices.

**Comment by Pierre-Gilles** [comment]
Ok, that was simple, the attribute "sensor" in deviceType is required :) ( see  https://github.com/GladysProject/Gladys/blob/master/api/models/DeviceType.js#L33 )

If your deviceType is a sensor, you should put true, else false. Here it's not a sensor but a deviceType your want to control so sensor should be put to false ( it will actually display a On/Off button )

**Comment by danships** [comment]
Thanks! The sensor attribute is missing in the Device.create() example in the gladys code (https://github.com/GladysProject/Gladys/tree/master/api/core/device/README.md) and I overlooked it in the other modules. Thanks for mentioning it.
